// export const LOGIN_USER = 'LOGIN_USER';
// export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
// export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
// export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';


export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING';
export const FETCH_CURRENT_USER_FULFILLED = 'FETCH_CURRENT_USER_FULFILLED';
export const FETCH_CURRENT_USER_REJECTED = 'FETCH_CURRENT_USER_REJECTED';
